version: '2'
services:
  es1: 
    image: es-cluster-node
    expose:
      - "1111"
      - "1112"
      - "2113"
      - "2114"
    ports:
      - "2113:2113"
    networks:
      escluster:
        ipv4_address: 172.16.238.11
    dns: 172.16.238.100
    environment:
      EVENTSTORE_INT_IP: 172.16.238.11
      EVENTSTORE_EXT_IP: 172.16.238.11
      EVENTSTORE_INT_TCP_PORT: 1111
      EVENTSTORE_EXT_TCP_PORT: 1112
      EVENTSTORE_INT_HTTP_PORT: 2113
      EVENTSTORE_EXT_HTTP_PORT: 2114
      EVENTSTORE_EXT_HTTP_PREFIXES: http://*:2113/

  dns-server:
    image: dns-server
    expose: 
      - "53/udp"
    networks:
      escluster:
        ipv4_address: 172.16.238.100

networks:
  escluster:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
